### ISSUE TITLE
Just tried to download

### ISSUE THREAD

**Issue by Wootster** [overfl0/Bulletproof-Arma-Launcher#180]
An error occurred in a subprocess:
Build: 3c9191ad2554950b6710397aa87950aac14b4251
Traceback (most recent call last):
  File "process.py", line 332, in _protected_call
  File "sync\preparer.py", line 253, in prepare_all
  File "sync\preparer.py", line 235, in run
  File "sync\preparer.py", line 59, in handle_messages
  File "sync\preparer.py", line 121, in on_mod_reuse_message
  File "sync\torrent_utils.py", line 291, in symlink_mod
  File "sync\torrent_utils.py", line 272, in prepare_mod_directory
  File "sync\torrent_utils.py", line 245, in ensure_directory_structure_is_correct
  File "sync\torrent_utils.py", line 224, in _replace_broken_junction_with_directory
  File "paths.py", line 220, in is_broken_junction
WindowsError: [Error 1921] The name of the file cannot be resolved by the system: u'D:\\SteamLibrary\\steamapps\\common\\Arma 3\\Addons\\@RHSUSAF\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\@CBA_A3\\*.*'

**Comment by overfl0** [comment]
Wow!

Are you sure you have not messed with:
1) The download directory? (like selecting the @RHSUSAF directory in OPTIONS [instead of a regular directory like "Frontline" or "TacBF"])
2) The directory contents itself?

The RHSUSAF directory should not contain CBA_A3, at least from what I know. So maybe you selected a wrong directory when the launcher was asking if CBA_A3 is somewhere on the disk?

So first, remove `D:\SteamLibrary\steamapps\common\Arma 3\Addons\@RHSUSAF\@CBA_A3` from the disk. Then, go to the directory that is set in OPTIONS and delete all the junctions-directories (the ones with the icon of a directory and an additional little arrow). Then re-run the launcher.

It would also help if you wrote here the directory that you have set in OPTIONS.

Tell me if that helped you.

**Comment by Wootster** [comment]
It's working now thanks :-)

**Comment by overfl0** [comment]
Cool :)
