### ISSUE TITLE
RuntimeError: Torrent already exists in session

### ISSUE THREAD

**Issue by overfl0** [overfl0/Bulletproof-Arma-Launcher#187]
While fiddling with seeding options

**Comment by overfl0** [comment]
Could not reproduce. Reopen if occurs again.

**Comment by overfl0** [comment]
```
Traceback (most recent call last):
  File "process.py", line 332, in _protected_call
  File "sync\manager_functions.py", line 401, in _sync_all
  File "sync\torrentsyncer.py", line 462, in sync
RuntimeError: torrent already exists in session
```
