### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Murray29ID** [overfl0/Bulletproof-Arma-Launcher#204]
when i try to install i get this issue:

An error occurred in a subprocess:
Build: 868ab94300ae059432b2d6f2ac1d09bfd9bf2d9f
Traceback (most recent call last):
  File "process.py", line 332, in _protected_call
  File "sync\preparer.py", line 254, in prepare_all
  File "sync\preparer.py", line 229, in run
  File "sync\preparer.py", line 187, in find_mods_and_ask
  File "sync\finder.py", line 131, in find_mods
  File "sync\torrent_utils.py", line 184, in path_can_be_a_mod
  File "ntpath.py", line 311, in expanduser
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 10: ordinal not in range(128)

**Comment by overfl0** [comment]
Thanks for the report, I'll look into it.

**Comment by overfl0** [comment]
Congratulations! You found a 3-year old python bug.
https://bugs.python.org/issue20140

This is fixed and will be released before the next organized game.
