### ISSUE TITLE
ClientQueryException: (...) Connection closed by Teamspeak client!

### ISSUE THREAD

**Issue by overfl0** [overfl0/Bulletproof-Arma-Launcher#216]
```
Build: 7b184b333a03bb2ebd5e619c380e0e527d8bb600
Traceback (most recent call last):
  File "view\errorpopup.py", line 80, in wrapper
  File "site-packages\kivy\app.py", line 828, in run
  File "site-packages\kivy\base.py", line 504, in runTouchApp
  File "site-packages\kivy\core\window\window_sdl2.py", line 646, in mainloop
  File "site-packages\kivy\core\window\window_sdl2.py", line 398, in _mainloop
  File "site-packages\kivy\base.py", line 342, in idle
  File "site-packages\kivy\base.py", line 327, in dispatch_input
  File "site-packages\kivy\base.py", line 293, in post_dispatch_input
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (c:\users\ieuser\appdata\local\temp\pip-entufs-build\kivy\_event.c:8191)
  File "site-packages\kivy\uix\behaviors\button.py", line 179, in on_touch_up
  File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (c:\users\ieuser\appdata\local\temp\pip-entufs-build\kivy\_event.c:8191)
  File "view\dynamicbutton.py", line 50, in on_release
  File "gui\installscreen.py", line 789, in on_play_button_release
  File "sync\modmanager.py", line 131, in run_the_game
  File "third_party\helpers.py", line 316, in run_the_game
  File "third_party\teamspeak.py", line 193, in run_and_connect
  File "third_party\clientquery.py", line 278, in get_TS_servers_connected
  File "third_party\clientquery.py", line 244, in get_servers_connected
  File "third_party\clientquery.py", line 216, in run_command
ClientQueryException: Teamspeak command: 'serverconnectionhandlerlist' returned error -2: Connection closed by Teamspeak client!
```

[20:32] MissVerstanden: I had ts open connected to another server. I tried closing Steam and starting steam before/after the launcher. then I closed ts and it worked.
[20:32] MissVerstanden: happened on the tacbf launcher
[20:32] MissVerstanden: would it be possible to show the player counts of the associated servers?
[20:58] Stack (Overflo): The close/open steam issue should not be present anymore, I've made a (hopefully working) workaround for it.

Was this a one time error or did you have it more than once?
[21:00] MissVerstanden: more then once
[21:01] MissVerstanden: just reproduced it :wink:
[21:03] MissVerstanden: ts open - connected to server -> does not work. ts open - not connected -> does not work. ts closed -> works
[21:04] MissVerstanden: by open I mean ts started and by closed not started :wink:

**Comment by overfl0** [comment]
MissVerstanden: some people have reported me that this happened after updating TeamSpeak and that restarting the PC fixed the issue.

Could you verify whether this fixes it for you, too?

**Comment by overfl0** [comment]
Note: This seems to be linked to TS version 3.1.3 which some people have and some do not (I don't). It's probably a rolling update because 3.1.2 is the version that can be downloaded from the official page now.

**Comment by overfl0** [comment]
![2017-03-25_18h40_50](https://cloud.githubusercontent.com/assets/1450333/24324665/d9a93c70-118a-11e7-8fe0-50571d9803dd.png)

Shit, they've added some API keys to talk with TS :(
That's probably the cause of all the problems so far

**Comment by overfl0** [comment]
Lol, the api is written down in plaintext in `clientquery.ini`, in the users' TS config directory. It should be very easy to locate that file and extract the api from the launcher :).
