### ISSUE TITLE
Exception when changing the background

### ISSUE THREAD

**Issue by overfl0** [overfl0/Bulletproof-Arma-Launcher#219]
```
Build: 0debef50f40b400f1e38e1e6248ca5d41d05f736
Traceback (most recent call last):
  File "view\errorpopup.py", line 82, in wrapper
  File "site-packages\kivy\app.py", line 828, in run
  File "site-packages\kivy\base.py", line 504, in runTouchApp
  File "site-packages\kivy\core\window\window_sdl2.py", line 646, in mainloop
  File "site-packages\kivy\core\window\window_sdl2.py", line 398, in _mainloop
  File "site-packages\kivy\base.py", line 339, in idle
  File "gui\mainwidget.py", line 127, in set_background_path
  File "kivy\weakproxy.pyx", line 33, in kivy.weakproxy.WeakProxy.setattr (c:\users\ieuser\appdata\local\temp\pip-entufs-build\kivy\weakproxy.c:1471)
  File "kivy\properties.pyx", line 423, in kivy.properties.Property.set (c:\users\ieuser\appdata\local\temp\pip-entufs-build\kivy\properties.c:5572)
  File "kivy\properties.pyx", line 461, in kivy.properties.Property.set (c:\users\ieuser\appdata\local\temp\pip-entufs-build\kivy\properties.c:6405)
  File "kivy\properties.pyx", line 516, in kivy.properties.Property.dispatch (c:\users\ieuser\appdata\local\temp\pip-entufs-build\kivy\properties.c:7105)
  File "kivy_event.pyx", line 1225, in kivy._event.Eve
```

Note: the stacktrace is only partial because the original submitter has not submitted the whole stacktrace

**Comment by overfl0** [comment]
Kivy sucks. Again.

https://github.com/kivy/kivy/pull/5155
