### ISSUE TITLE
Frontline: Manual Detection Of Mods Not Working

### ISSUE THREAD

**Issue by BushmanG** [overfl0/Bulletproof-Arma-Launcher#244]
An error occurred in a subprocess:
Build: 0debef50f40b400f1e38e1e6248ca5d41d05f736
Traceback (most recent call last):
  File "process.py", line 342, in _protected_call
  File "sync\manager_functions.py", line 75, in symlink_mod
  File "sync\torrent_utils.py", line 420, in symlink_mod
  File "sync\torrent_utils.py", line 370, in create_symlink
  File "subprocess.py", line 186, in check_call
CalledProcessError: Command '['cmd', '/c', 'mklink', '/J', 'F:\\Steam\\SteamLibrary\\steamapps\\common\\Arma 3\\Frontline\\@CUP Terrains - Core', 'F:\\ARMA 3 MODS\\@cup_terrains_core']' returned non-zero exit status 1

This is what pops up when I try to recognize mods I already have installed on my PC. Any ideas?

Cheers
Brett

**Comment by overfl0** [comment]
You closed the issue. Have you fixed the problem? If you did, what was the cause?
