### ISSUE TITLE
Launcher bug 

### ISSUE THREAD

**Issue by HiGHBurrito** [overfl0/Bulletproof-Arma-Launcher#245]
Told me to post this here, So...

An error occurred in a subprocess:
Build: ad97b4dd1f5fbb0f06288aafa451ea553cb15721
Traceback (most recent call last):
  File "process.py", line 430, in _protected_call
  File "sync\preparer.py", line 260, in prepare_all
  File "sync\preparer.py", line 242, in run
  File "sync\preparer.py", line 59, in handle_messages
  File "sync\preparer.py", line 126, in on_mod_reuse_message
KeyError: <Mod: @IFA3_AIO_LITE -- utcts: 2017-04-22 00:14:27 -- optional: False -- selected: False -- IFA3 All in One -- durl: http://launcher.frontline.frl/torrents/@IFA3_AIO_LITE-2017-04-21_1492820067.torrent -- version: 0>

**Comment by HiGHBurrito** [comment]
For clarification, I am not having this error anymore.

**Comment by overfl0** [comment]
So the next time you restarted the launcher, everything installed fine, right?

I'll take as look at that issue.

**Comment by HiGHBurrito** [comment]
Didn't even have to restart to fix it, Just worked after pressing install again.

**Comment by overfl0** [comment]
Hey, in case I don't figure it out by myself, by looking at the code, could you zip me the files that are located at `c:\users\<username>\.kivy\logs` and send them to me somehow (or attach them to this issue) along with a small description of what you were doing at the time and when that error happened exactly?

Did you do something that could have been classified as "out of the ordinary"? :)

Also, giving me an approximate date and time will make it easier for me to go through the logs.

**Comment by overfl0** [comment]
I think the only reason for this problem to happen could be that the graphics library (goddammit you, Kivy, again!) registered two clicks on the "use this mod" button because you double-clicked very fast.

Could this have been this cause?
