### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by Hatamoose** [overfl0/Bulletproof-Arma-Launcher#249]
An error occurred in a subprocess:
Build: ad97b4dd1f5fbb0f06288aafa451ea553cb15721
Traceback (most recent call last):
  File "process.py", line 430, in _protected_call
  File "sync\manager_functions.py", line 443, in _sync_all
  File "sync\torrentsyncer.py", line 509, in sync
  File "sync\torrentsyncer.py", line 459, in handle_messages
OverflowError: Python int too large to convert to C long

**Comment by overfl0** [comment]
Could you tell what you did prior to this error happening?
Have you put a big number in the "maximum download/upload speed" box, by chance?

**Comment by Hatamoose** [comment]
Thats exactly what I did

**Comment by Hatamoose** [comment]
I guess I'll fix that. Thanks. LOL
