### ISSUE TITLE
Another error just reported

### ISSUE THREAD

**Issue by overfl0** [overfl0/Bulletproof-Arma-Launcher#255]
```
An error occurred in a subprocess:
Build: 8a83adaa26217c45b541f4e90b535f2fb7d65fce
Traceback (most recent call last):
  File "process.py", line 430, in _protected_call
  File "sync\torrent_uploader.py", line 100, in make_torrent
  File "sync\torrent_uploader.py", line 201, in _make_torrent
  File "sync\torrent_uploader.py", line 271, in perform_update
  File "remote.py", line 178, in read_file
  File "site-packages\paramiko\sftp_client.py", line 338, in open
  File "site-packages\paramiko\sftp_client.py", line 774, in _request
  File "site-packages\paramiko\sftp_client.py", line 826, in _read_response
  File "site-packages\paramiko\sftp_client.py", line 859, in _convert_status
IOError: Failure
```

**Comment by jonpas** [comment]
Caused by wrong `server_torrents_path` devmode config.

`server_torrents_path` and `server_metadata_path` also require absolute path on Windows servers, might be something to add to the wiki.
